server:
  port: 8071	

spring:
  application:
    name: configserver
  profiles:
    #active: native
    active: git	
  cloud:
    config:
      server:
        #native:
          #search-location: "classpath:/config"
          #search-location: "file:///C://Spring boot files//microservice-course-easybytes//section-6//v2-spring-cloud-config//config"
        git:
          uri: "https://github.com/asadk29/configrepo.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
encrypt:
  key: "737huy888u2ihjd"
   
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
